"""Schéma déclaratif du profil : un champ = (nom, type, choix, catégorie).

Types reconnus : "date", "float", "bool", "enum", "text", "code_postal".
`choix` n'est utilisé que pour le type "enum" (liste de valeurs acceptées).
La catégorie sert uniquement à regrouper l'affichage dans le récap.
"""

CHAMPS_PERSONNE_A_CHARGE = [
    ("date_naissance", "date", None),
    ("lien", "enum", ["enfant", "autre"]),
    ("scolarise", "bool", None),
    ("situation_handicap", "bool", None),
    ("garde_alternee", "bool", None),
]

SCHEMA = [
    ("date_naissance", "date", None, "Identité"),
    ("situation_familiale", "enum",
     ["célibataire", "concubinage", "pacsé·e", "marié·e", "divorcé·e", "veuf·ve"], "Identité"),
    ("nombre_parts_fiscales", "float", None, "Foyer"),
    ("code_postal", "code_postal", None, "Logement"),
    ("commune", "text", None, "Logement"),
    ("statut_logement", "enum",
     ["locataire", "propriétaire", "hébergé·e à titre gratuit", "sans domicile stable"], "Logement"),
    ("residence", "enum", ["principale", "secondaire"], "Logement"),
    ("loyer_mensuel", "float", None, "Logement"),
    ("mensualite_pret_immobilier", "float", None, "Logement"),
    ("zone_faibles_emissions", "bool", None, "Logement"),
    ("revenu_net_mensuel_foyer", "float", None, "Ressources"),
    ("revenu_fiscal_reference", "float", None, "Ressources"),
    ("type_revenus", "text", None, "Ressources"),
    ("patrimoine_epargne", "float", None, "Ressources"),
    ("autre_bien_immobilier", "bool", None, "Ressources"),
    ("aides_deja_percues", "text", None, "Ressources"),
    ("frais_garde_enfants", "float", None, "Dépenses"),
    ("pension_alimentaire_versee", "float", None, "Dépenses"),
    ("pension_alimentaire_recue", "float", None, "Dépenses"),
    ("statut_professionnel", "enum", [
        "salarié·e", "indépendant·e-auto-entrepreneur·se", "demandeur·se d'emploi",
        "étudiant·e", "apprenti·e-alternant·e", "retraité·e", "sans activité",
    ], "Situation professionnelle"),
    ("anciennete_statut", "text", None, "Situation professionnelle"),
    ("inscrit_france_travail", "bool", None, "Situation professionnelle"),
    ("indemnise_chomage", "bool", None, "Situation professionnelle"),
    ("niveau_etudes", "enum", [
        "lycée", "BTS-DUT", "licence", "master", "doctorat", "formation sanitaire-sociale", "autre",
    ], "Situation professionnelle"),
    ("boursier", "bool", None, "Situation professionnelle"),
    ("echelon_bourse", "text", None, "Situation professionnelle"),
    ("entreprise_secteur", "enum", ["public", "privé"], "Situation professionnelle"),
    ("situation_handicap", "bool", None, "Situations particulières"),
    ("taux_incapacite", "float", None, "Situations particulières"),
    ("situation_perte_autonomie", "bool", None, "Situations particulières"),
    ("utilise_transports_commun", "bool", None, "Mobilité"),
    ("reseau_transport_principal", "enum",
     ["SNCF", "réseau urbain", "réseau régional", "plusieurs"], "Mobilité"),
    ("carte_etudiante_scolaire", "bool", None, "Mobilité"),
    ("projet_vehicule_electrique", "bool", None, "Projets"),
    ("type_projet_vehicule", "enum",
     ["achat neuf", "achat occasion", "location longue durée"], "Projets"),
    ("vehicule_actuel_a_mettre_a_la_casse", "bool", None, "Projets"),
    ("projet_velo", "bool", None, "Projets"),
    ("type_velo", "enum", ["électrique", "cargo", "pliant", "adapté handicap"], "Projets"),
    ("projet_achat_logement", "bool", None, "Projets"),
    ("primo_accedant", "bool", None, "Projets"),
    ("projet_renovation_energetique", "bool", None, "Projets"),
    ("type_travaux_envisages", "enum",
     ["isolation", "chauffage", "fenêtres", "plusieurs"], "Projets"),
    ("pratique_sportive_reguliere", "bool", None, "Pratiques"),
    ("frequentation_culturelle", "bool", None, "Pratiques"),
]

LIBELLES = {
    "date_naissance": "Date de naissance",
    "situation_familiale": "Situation familiale",
    "nombre_parts_fiscales": "Nombre de parts fiscales",
    "code_postal": "Code postal",
    "commune": "Commune",
    "statut_logement": "Statut du logement",
    "residence": "Résidence principale ou secondaire",
    "loyer_mensuel": "Loyer mensuel",
    "mensualite_pret_immobilier": "Mensualité de prêt immobilier",
    "zone_faibles_emissions": "En zone à faibles émissions (ZFE)",
    "revenu_net_mensuel_foyer": "Revenu net mensuel du foyer",
    "revenu_fiscal_reference": "Revenu fiscal de référence",
    "type_revenus": "Type de revenus",
    "patrimoine_epargne": "Patrimoine / épargne",
    "autre_bien_immobilier": "Autre bien immobilier",
    "aides_deja_percues": "Aides déjà perçues",
    "frais_garde_enfants": "Frais de garde d'enfants",
    "pension_alimentaire_versee": "Pension alimentaire versée",
    "pension_alimentaire_recue": "Pension alimentaire reçue",
    "statut_professionnel": "Statut professionnel",
    "anciennete_statut": "Ancienneté dans ce statut",
    "inscrit_france_travail": "Inscrit·e à France Travail",
    "indemnise_chomage": "Indemnisé·e chômage",
    "niveau_etudes": "Niveau d'études",
    "boursier": "Boursier·ère",
    "echelon_bourse": "Échelon de bourse",
    "entreprise_secteur": "Secteur de l'entreprise (alternance)",
    "situation_handicap": "Situation de handicap",
    "taux_incapacite": "Taux d'incapacité",
    "situation_perte_autonomie": "Situation de perte d'autonomie",
    "utilise_transports_commun": "Utilise les transports en commun",
    "reseau_transport_principal": "Réseau de transport principal",
    "carte_etudiante_scolaire": "Carte étudiante/scolaire",
    "projet_vehicule_electrique": "Projet de véhicule électrique",
    "type_projet_vehicule": "Type de projet véhicule",
    "vehicule_actuel_a_mettre_a_la_casse": "Véhicule actuel à mettre à la casse",
    "projet_velo": "Projet vélo",
    "type_velo": "Type de vélo",
    "projet_achat_logement": "Projet d'achat de logement",
    "primo_accedant": "Primo-accédant·e",
    "projet_renovation_energetique": "Projet de rénovation énergétique",
    "type_travaux_envisages": "Type de travaux envisagés",
    "pratique_sportive_reguliere": "Pratique sportive régulière",
    "frequentation_culturelle": "Fréquentation culturelle",
    "lien": "Lien",
    "scolarise": "Scolarisé·e",
    "garde_alternee": "Garde alternée",
}

ORDRE_CATEGORIES = [
    "Identité", "Foyer", "Logement", "Ressources", "Dépenses",
    "Situation professionnelle", "Situations particulières", "Mobilité",
    "Projets", "Pratiques",
]
